### ISSUE TITLE
project directory not required

### ISSUE THREAD

**Issue by marinkobabic** [Ragin-LundF/k8s-jcasc-management-go#23]
Why do you need to persist all the yaml file into the projects directory? 

In generally the project definition is pure configuration. Not more and not less. So when somebody creates a project all is required

- persist the new configuration into configuration files: (namespace, ip, jenkins system message, jobs repository, pvc, templates)
- update the configuration in the models (actually an restart of the application is required)

When the deployment is started, then you can always rely on the newest charts for the installation, update. Then you can temporary create all the yaml files and do the installation.

- For the delete you just need the release name
- If all the yaml files are needed you can get them always from the cluster ```helm` get all "release" -n `"namespace"```

If you for some reason think that the project files are required, then you should provide an option to update them, but actually I see no value of having them versioned in the repository.

**Comment by Ragin-LundF** [comment]
The project creator is only a little helper. In the project, it can happen, that somebody wants to change special things. This makes possibly every project unique, based on the same source.
They are only the "values.yaml" files of the applications.

But anyway.
It is also possible to provide both.

Full "values.yaml" files and only configuration for standard deployments, which always is using the configured templates.

**Comment by marinkobabic** [comment]
I think you can keep the entered input in a json formatted file. Actually
you are doing this with the project name and the used ip. This should be
fully independent of the used helm chart and values.yaml. If somebody wants
to keep the generated project yaml files, so you could provide in the
settings a flag therefore.

By default there are no adjustments required because we are following a
standard. You can at any point switch to whatever helm chart and the
entered input can be easily be reused to update an existing installation.

**Comment by Ragin-LundF** [comment]
Naaaa....not every project is like the other. So maybe for the most cases, it makes sense to use only the configuration and create the YAML's only temporary.

But this depends also on the setup.

Example:
- JCasC files are often individual and can change. It is good to have them as they are to know which exact configuration was working at some time
- Nginx configuration is something, that is more or less fully abstractable with JSON like you mentioned. But it is about some fields...so the benefit of using a JSON configuration instead of the YAML configuration is not really there.
- Jenkins values.yaml is the opposite. This will maybe every time the same, here it can make sense to have less "visible configuration"

For uninstalling the system only checks which files are existing to see what was installed because the installation is split into Jenkins, Ingress Controller, and load balancer installation.

Here the system detects only what was available. So the concrete helm charts/values are not used. But you are right, if you say, that it is better to have such stuff in a configuration which decouples the dependency on the existing files.

I do not want to remove the possibility of project-specific changes completely.

An approach can be to offer some radio boxes like "available as individual configuration files".
Then the global configuration is in the lead for the common stuff (which systems are deployed, what was the release name, IP, namespace....) and the system checks, which files are available in the file system.
If it founds a file in the expected project directory, this will overwrite the common template (but it will be checked for open template variables to replace e.g. the namespace or IP).

This makes it possible to avoid many project directories for standard environments and keeps the flexibility to change the yaml files for individual requirements.

**Comment by marinkobabic** [comment]
When talking about the values, then only the values you entered during the
project creation. Then json is the appropriate format. What are you using
this values for nobody cares about it.

You don't need the files to detect what was installed. Just persist the
releases used including the state. You are running always helm to get them
installed and to retrieve the used values for every release. During the
uninstall process you need only the information from project and the
release names.

From my point of view keep the files as long as you have the decoupling
described above and you are reloading the configuration immediately after
the project creation without restarting the app.

From my point of view templates should be used for customization. Otherwise
all the manual changes need to be done again and again for every release.

**Comment by Ragin-LundF** [comment]
Reloading the data after project creation is not so easy at the moment. The problem here is the underlying UI framework. They are working currently on data binding, which makes it easier.
Anyway, on develop I've introduced a new event-based update of the components and a reload of the configuration to have the namespaces directly available.
But I have to work a little bit more on this topic because currently, the refresh of the drop-downs and the refresh of the tabs (parent views) have to work in the correct order. Else the drop-down button is not every time on the end of the view.

Maybe I introduce the release check instead of the file check in the next days. But both are independent of the configuration ;).
