### ISSUE TITLE
More flexibility for secrets

### ISSUE THREAD

**Issue by marinkobabic** [Ragin-LundF/k8s-jcasc-management-go#25]
Actually there is only one global secrets file in the secrets folder. We are not able to handle all the use cases by just having one file. When creating a namespace for QA, INTEGRATION or DEV different secrets are required. This is depending on the target environment and/or cluster. 

Solution proposal:

- Secrets are located in the secrets folder. When dealing with the secrets all the secrets filenames should be displayed in the UI (checkbox). So that they can be encrypted and decrypted depending on the selection.
- When creating a namespace, then the secrets should be selected which are required for the namespace creation. 

- All of them have the same password for encryption and decryption. 

- The secret with the name **global** is always by default selected

**Comment by Ragin-LundF** [comment]
https://github.com/Ragin-LundF/k8s-jcasc-management-go/tree/feature/support_for_multiple_secrets

**Comment by Ragin-LundF** [comment]
The solution uses a select box. Every environment has its own secrets with that.
With the checkboxes, the UI will become a bit clumsy and it is not always clear which secrets should be applied.

Select boxes have the disadvantage that secrets files may contain duplicates of other secret files, but it is more bulletproof for users which are not so experienced with the used platforms. With that, there is no need to create large documentations like "if you use env a, then you need to select the secrets f, g, and z"

**Comment by marinkobabic** [comment]
SelectBox means I can just select one secret per environment? The idea was to select multiple secrets per environment.

**Comment by marinkobabic** [comment]
Normally we should have

- clusters
- secrets
- stagings
- projects

1. every project has multiple staging environments
2. a staging is sit, qa, ref, preview or dev
3. a staging dev can be deployed to cluster A, staging sit to cluster B and stating qa to cluster C. The assignment will be done manually by the guy setting up the project
4. some secrets are cluster specific and some are staging specific. So normally this is something what should be configured in advance before setting up the project
5. A project contains multiple staging environments

Therefore normally the kubeconfig should not be used. You should provide an option to configure all the clusters, certificates and tokens as part of configuration. Then this information can be used by all when knowing the password for the secrets which should be requested when starting up the tool.

The config file you have today has to be setup manually. Normally the tool should provide a settings screen where all the configuration can be set. No manual changes somewhere in a file except the secrets files. Just to give you some idea about the further development of the tool :-)

**Comment by Ragin-LundF** [comment]
> SelectBox means I can just select one secret per environment? The idea was to select multiple secrets per environment.

The problem with that is, that you have to document it all and it makes everything a bit more unstable. If you only have to select the environment secrets, it is easier to follow.

Like you have described in your last comment, it needs a bit more configuration to provide a setting, where this makes sense.
The development will go in this direction, but for that, some other things are needed to be changed before. I would also introduce some kind of grouping/hierarchy tree view for the environments, to give the users a better overview of which environment which project was meant for.
All of those things will result in some kind of "project configuration". But I don't want to change this too often, because it needs more manual migration.

> Therefore normally the kubeconfig should not be used.
This is the easiest way to configure everything because there is no need to add too many parameters to kubectl, which makes it easier to follow which commands exactly were executed if there are problems.

The idea to set up an environment with a token sounds good as an alternative. I will keep track of this as part of an advanced configuration.

> The config file you have today has to be setup manually.
Yes and no ;). There is a default and it is only needed to overwrite necessary changes for a k8s-jcasc-mgmt project.
But a configuration screen for it sounds not bad, but then I have to think about the CLI version (maybe in the case of CLI it is ok to write a config file by hand).

Let's see. This version is able to help you work with different secrets for different clusters.
There is a lot of space to the top to optimize the process, but I would avoid making it too complex if possible, that it is usable for everybody. The current configuration is complex enough ;).

I will create some tickets in the next days because now I have a bit more time for this tool after I had finished the most required changes in the BDD-library.
But first I have to think about how this fits best into the whole setup with CLI and GUI tool under the hood. My last thought about this topic was to split it into several projects (core, CLI, and GUI) which allows some differences between the tools in the usage but with support of the same configuration. But this also makes the development harder.

**Comment by marinkobabic** [comment]
I think in generally you should get rid of the CLI and GUI tool. This looks like technical implementation for technical guys. I would go with a web UI and the deployment as docker, Kubernetes. This way the devops guys can access the tool just by using the browser. This is one of the reasons why everything must be configurable in the UI. Argo CD is following the same approach. Say bye bye to the horrible UIs 😄
